import type { Service } from './types';

export const defaultServices: Service[] = [
  {
    name: 'Netflix',
    logo: 'services/netflix.svg',
    url: 'https://netflix.com/browse',
    color: '#e50914',
    style: {},
    permissions: [],
  },
  {
    name: 'YouTube',
    logo: 'services/youtube.svg',
    url: 'https://youtube.com',
    color: '#ff0000',
    style: {},
    permissions: ['media'],
  },
  {
    name: 'YouTube Music',
    logo: 'services/youtube.svg',
    url: 'https://music.youtube.com',
    color: '#ff0000',
    style: {},
    permissions: ['media'],
  },
  {
    name: 'Twitch',
    logo: 'services/twitch.svg',
    url: 'https://twitch.tv',
    color: '#6441a5',
    style: {},
    permissions: ['media'],
  },
  {
    name: 'Amazon Prime Video',
    logo: 'services/primevideo.svg',
    url: 'https://www.primevideo.com',
    color: '#00A8E1',
    style: {},
    permissions: ['media'],
  },
  {
    name: 'HBO Max',
    logo: 'services/hbomax.svg',
    url: 'https://www.max.com',
    color: '#b535f6',
    style: {},
    permissions: [],
  },
  {
    name: 'Apple TV',
    logo: 'services/appletv.svg',
    url: 'https://tv.apple.com',
    color: '#ffffff',
    style: {},
    permissions: [],
  },
  {
    name: 'Crunchyroll',
    logo: 'services/crunchyroll.svg',
    url: 'https://crunchyroll.com',
    color: '#ffe600',
    style: {},
    permissions: [],
  },
  {
    name: 'Floatplane',
    hidden: true,
    logo: 'services/floatplane.svg',
    url: 'https://floatplane.com/',
    color: '#00aeef',
    style: {},
    permissions: [],
  },
  {
    name: 'Disney+',
    hidden: true,
    logo: 'services/disney.svg',
    url: 'https://www.disneyplus.com/',
    color: '#ffffff',
    style: {},
    permissions: [],
  },
];
